

simulatorRate: 50 # Hz

useMap: True
useLidar: True

map:
  path: ""
  origin: [0, 0, 0] # m
  # path: "maps/iROS23.png"
  # origin: [-16.638911, -1.603149, 0.000000] # m
  publishMap: True
  mapTopic: "/map"
  mapFrame: "map"
  mapRate: 1 # Hz
  resolution: 0.025000 # m/cell
  occupied_thresh: 0.196
  wallBuffer: 0.15 # m
  obstacles: 
    timeout: 5 # s
    list: [] # list of obstacles
    # list: # list of obstacles
    #   - [[1.68, 0.64], [3.06, 0.62], [2.94, 1.58], [1.64, 1.62]]
    #   - [[6.12, 0.38], [6.26, -0.39], [7.62, -0.1], [7.5, 0.7]]
    #   - [[5.56,3.25],[4.25,2.20],[4.6,1.44],[6.05,2.61]]
    #   - [[-1.74, 4.32], [-1.74, 3.52], [-0.3, 3.48], [-0.2, 4.38]]
    #   - [[-9.24, 5.4], [-9.36, 4.6], [-8.12, 4.32], [-7.86, 5.0]]
    #   - [[-14.04, 3.32], [-13.16, 3.2], [-12.72, 3.96], [-13.32, 4.52]]
    #   - [[-11.96, 1.66], [-12.54, 1.06], [-11.74, 0.24], [-10.92, 0.76]]
    #   - [[-8.9, -0.24], [-8.84, -1.04], [-7.7, -1.0], [-7.66, -0.2]]
    #   - [[-3.82, -0.1], [-3.94, -0.96], [-2.38, -0.98], [-2.42, -0.02]] 
  checkpoints: 
    threshold: 1 # m
    list:  # list of checkpoints
     - [0,0]
     - [7.5,3]
     - [-1,4.5]
     - [-13,2]

cars: ["car_1"]
  
car_1:
  invertSteering: True
  WB: 0.324 # wheel base (m)
  steeringMax: 0.6 # max steering angle (rad)
  lidar:
    updateRate: 40 # Hz
    angleMin: -2.35619 # -135 degrees
    angleMax: 2.35619 # 135 degrees
    angleIncrement: 0.00436332 # 0.25 degrees
    rangeMin: 0.1 # m
    rangeMax: 30.0 # m
